// Code generated by ent, DO NOT EDIT.

package middleware

const (
	// Label holds the string label denoting the middleware type in the database.
	Label = "middleware"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLID holds the string denoting the l_id field in the database.
	FieldLID = "l_id"
	// FieldDID holds the string denoting the d_id field in the database.
	FieldDID = "d_id"
	// FieldSysID holds the string denoting the sys_id field in the database.
	FieldSysID = "sys_id"
	// Table holds the table name of the middleware in the database.
	Table = "middlewares"
)

// Columns holds all SQL columns for middleware fields.
var Columns = []string{
	FieldID,
	FieldLID,
	FieldDID,
	FieldSysID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
