version: '3' # composeファイルのバージョン
services:
  go-test:
    container_name: go-test
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./src:/go/src/
    tty: true
    ports:
        - 3000:3000
    environment:
      - TZ=Asia/Tokyo
  db:
    container_name: db
    image: postgres:14.6
    ports:
      - 5432:5432
    volumes:
      - go-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: "db"
      TZ: "Asia/Tokyo"
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: hoge@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
volumes:
  go-db:
  pgadmin4_data:
