version: '3' # composeファイルのバージョン
services:
  go-test:
    container_name: go-test
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./src:/go/src/
    tty: true
    environment:
      - TZ=Asia/Tokyo
  db:
    container_name: db
    image: postgres:14.6
    ports:
      - 5432:5432
    volumes:
      - go-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: "db"
      TZ: "Asia/Tokyo"
volumes:
  go-db:
