// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Middleware is the predicate function for middleware builders.
type Middleware func(*sql.Selector)
