package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"go-test/graph/model"
	middlewareRepo "go-test/repos"
	createLUsecase "go-test/usecase"
)

// CreateL is the resolver for the createL field.
func (r *mutationResolver) CreateL(ctx context.Context, input model.CreateLIdInput) (int, error) {
	repo := middlewareRepo.NewMiddlewareRepo()
	usecase := createLUsecase.NewCreateLUsecase(repo)
	result, err := usecase.CreateL(ctx, input.LID)
	return result, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
