// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-test/ent/middleware"
	"go-test/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MiddlewareQuery is the builder for querying Middleware entities.
type MiddlewareQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Middleware
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiddlewareQuery builder.
func (mq *MiddlewareQuery) Where(ps ...predicate.Middleware) *MiddlewareQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit adds a limit step to the query.
func (mq *MiddlewareQuery) Limit(limit int) *MiddlewareQuery {
	mq.limit = &limit
	return mq
}

// Offset adds an offset step to the query.
func (mq *MiddlewareQuery) Offset(offset int) *MiddlewareQuery {
	mq.offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MiddlewareQuery) Unique(unique bool) *MiddlewareQuery {
	mq.unique = &unique
	return mq
}

// Order adds an order step to the query.
func (mq *MiddlewareQuery) Order(o ...OrderFunc) *MiddlewareQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// First returns the first Middleware entity from the query.
// Returns a *NotFoundError when no Middleware was found.
func (mq *MiddlewareQuery) First(ctx context.Context) (*Middleware, error) {
	nodes, err := mq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{middleware.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MiddlewareQuery) FirstX(ctx context.Context) *Middleware {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Middleware ID from the query.
// Returns a *NotFoundError when no Middleware ID was found.
func (mq *MiddlewareQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{middleware.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MiddlewareQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Middleware entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Middleware entity is found.
// Returns a *NotFoundError when no Middleware entities are found.
func (mq *MiddlewareQuery) Only(ctx context.Context) (*Middleware, error) {
	nodes, err := mq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{middleware.Label}
	default:
		return nil, &NotSingularError{middleware.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MiddlewareQuery) OnlyX(ctx context.Context) *Middleware {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Middleware ID in the query.
// Returns a *NotSingularError when more than one Middleware ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MiddlewareQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{middleware.Label}
	default:
		err = &NotSingularError{middleware.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MiddlewareQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Middlewares.
func (mq *MiddlewareQuery) All(ctx context.Context) ([]*Middleware, error) {
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mq *MiddlewareQuery) AllX(ctx context.Context) []*Middleware {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Middleware IDs.
func (mq *MiddlewareQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mq.Select(middleware.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MiddlewareQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MiddlewareQuery) Count(ctx context.Context) (int, error) {
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MiddlewareQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MiddlewareQuery) Exist(ctx context.Context) (bool, error) {
	if err := mq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MiddlewareQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiddlewareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MiddlewareQuery) Clone() *MiddlewareQuery {
	if mq == nil {
		return nil
	}
	return &MiddlewareQuery{
		config:     mq.config,
		limit:      mq.limit,
		offset:     mq.offset,
		order:      append([]OrderFunc{}, mq.order...),
		predicates: append([]predicate.Middleware{}, mq.predicates...),
		// clone intermediate query.
		sql:    mq.sql.Clone(),
		path:   mq.path,
		unique: mq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LID string `json:"l_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Middleware.Query().
//		GroupBy(middleware.FieldLID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *MiddlewareQuery) GroupBy(field string, fields ...string) *MiddlewareGroupBy {
	grbuild := &MiddlewareGroupBy{config: mq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mq.sqlQuery(ctx), nil
	}
	grbuild.label = middleware.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LID string `json:"l_id,omitempty"`
//	}
//
//	client.Middleware.Query().
//		Select(middleware.FieldLID).
//		Scan(ctx, &v)
func (mq *MiddlewareQuery) Select(fields ...string) *MiddlewareSelect {
	mq.fields = append(mq.fields, fields...)
	selbuild := &MiddlewareSelect{MiddlewareQuery: mq}
	selbuild.label = middleware.Label
	selbuild.flds, selbuild.scan = &mq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a MiddlewareSelect configured with the given aggregations.
func (mq *MiddlewareQuery) Aggregate(fns ...AggregateFunc) *MiddlewareSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MiddlewareQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mq.fields {
		if !middleware.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MiddlewareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Middleware, error) {
	var (
		nodes = []*Middleware{}
		_spec = mq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Middleware).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Middleware{config: mq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mq *MiddlewareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Node.Columns = mq.fields
	if len(mq.fields) > 0 {
		_spec.Unique = mq.unique != nil && *mq.unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MiddlewareQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (mq *MiddlewareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   middleware.Table,
			Columns: middleware.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: middleware.FieldID,
			},
		},
		From:   mq.sql,
		Unique: true,
	}
	if unique := mq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, middleware.FieldID)
		for i := range fields {
			if fields[i] != middleware.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MiddlewareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(middleware.Table)
	columns := mq.fields
	if len(columns) == 0 {
		columns = middleware.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.unique != nil && *mq.unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MiddlewareGroupBy is the group-by builder for Middleware entities.
type MiddlewareGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MiddlewareGroupBy) Aggregate(fns ...AggregateFunc) *MiddlewareGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mgb *MiddlewareGroupBy) Scan(ctx context.Context, v any) error {
	query, err := mgb.path(ctx)
	if err != nil {
		return err
	}
	mgb.sql = query
	return mgb.sqlScan(ctx, v)
}

func (mgb *MiddlewareGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range mgb.fields {
		if !middleware.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mgb *MiddlewareGroupBy) sqlQuery() *sql.Selector {
	selector := mgb.sql.Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mgb.fields)+len(mgb.fns))
		for _, f := range mgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mgb.fields...)...)
}

// MiddlewareSelect is the builder for selecting fields of Middleware entities.
type MiddlewareSelect struct {
	*MiddlewareQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MiddlewareSelect) Aggregate(fns ...AggregateFunc) *MiddlewareSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MiddlewareSelect) Scan(ctx context.Context, v any) error {
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	ms.sql = ms.MiddlewareQuery.sqlQuery(ctx)
	return ms.sqlScan(ctx, v)
}

func (ms *MiddlewareSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(ms.sql))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ms.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ms.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ms.sql.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
