// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-test/ent/middleware"
	"go-test/ent/predicate"
	"sync"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMiddleware = "Middleware"
)

// MiddlewareMutation represents an operation that mutates the Middleware nodes in the graph.
type MiddlewareMutation struct {
	config
	op            Op
	typ           string
	id            *int
	l_id          *string
	d_id          *string
	sys_id        *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Middleware, error)
	predicates    []predicate.Middleware
}

var _ ent.Mutation = (*MiddlewareMutation)(nil)

// middlewareOption allows management of the mutation configuration using functional options.
type middlewareOption func(*MiddlewareMutation)

// newMiddlewareMutation creates new mutation for the Middleware entity.
func newMiddlewareMutation(c config, op Op, opts ...middlewareOption) *MiddlewareMutation {
	m := &MiddlewareMutation{
		config:        c,
		op:            op,
		typ:           TypeMiddleware,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMiddlewareID sets the ID field of the mutation.
func withMiddlewareID(id int) middlewareOption {
	return func(m *MiddlewareMutation) {
		var (
			err   error
			once  sync.Once
			value *Middleware
		)
		m.oldValue = func(ctx context.Context) (*Middleware, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Middleware.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMiddleware sets the old Middleware of the mutation.
func withMiddleware(node *Middleware) middlewareOption {
	return func(m *MiddlewareMutation) {
		m.oldValue = func(context.Context) (*Middleware, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MiddlewareMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MiddlewareMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MiddlewareMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MiddlewareMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Middleware.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetLID sets the "l_id" field.
func (m *MiddlewareMutation) SetLID(s string) {
	m.l_id = &s
}

// LID returns the value of the "l_id" field in the mutation.
func (m *MiddlewareMutation) LID() (r string, exists bool) {
	v := m.l_id
	if v == nil {
		return
	}
	return *v, true
}

// OldLID returns the old "l_id" field's value of the Middleware entity.
// If the Middleware object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MiddlewareMutation) OldLID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLID: %w", err)
	}
	return oldValue.LID, nil
}

// ResetLID resets all changes to the "l_id" field.
func (m *MiddlewareMutation) ResetLID() {
	m.l_id = nil
}

// SetDID sets the "d_id" field.
func (m *MiddlewareMutation) SetDID(s string) {
	m.d_id = &s
}

// DID returns the value of the "d_id" field in the mutation.
func (m *MiddlewareMutation) DID() (r string, exists bool) {
	v := m.d_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDID returns the old "d_id" field's value of the Middleware entity.
// If the Middleware object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MiddlewareMutation) OldDID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDID: %w", err)
	}
	return oldValue.DID, nil
}

// ResetDID resets all changes to the "d_id" field.
func (m *MiddlewareMutation) ResetDID() {
	m.d_id = nil
}

// SetSysID sets the "sys_id" field.
func (m *MiddlewareMutation) SetSysID(s string) {
	m.sys_id = &s
}

// SysID returns the value of the "sys_id" field in the mutation.
func (m *MiddlewareMutation) SysID() (r string, exists bool) {
	v := m.sys_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSysID returns the old "sys_id" field's value of the Middleware entity.
// If the Middleware object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MiddlewareMutation) OldSysID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSysID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSysID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSysID: %w", err)
	}
	return oldValue.SysID, nil
}

// ResetSysID resets all changes to the "sys_id" field.
func (m *MiddlewareMutation) ResetSysID() {
	m.sys_id = nil
}

// Where appends a list predicates to the MiddlewareMutation builder.
func (m *MiddlewareMutation) Where(ps ...predicate.Middleware) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *MiddlewareMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Middleware).
func (m *MiddlewareMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MiddlewareMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.l_id != nil {
		fields = append(fields, middleware.FieldLID)
	}
	if m.d_id != nil {
		fields = append(fields, middleware.FieldDID)
	}
	if m.sys_id != nil {
		fields = append(fields, middleware.FieldSysID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MiddlewareMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case middleware.FieldLID:
		return m.LID()
	case middleware.FieldDID:
		return m.DID()
	case middleware.FieldSysID:
		return m.SysID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MiddlewareMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case middleware.FieldLID:
		return m.OldLID(ctx)
	case middleware.FieldDID:
		return m.OldDID(ctx)
	case middleware.FieldSysID:
		return m.OldSysID(ctx)
	}
	return nil, fmt.Errorf("unknown Middleware field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MiddlewareMutation) SetField(name string, value ent.Value) error {
	switch name {
	case middleware.FieldLID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLID(v)
		return nil
	case middleware.FieldDID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDID(v)
		return nil
	case middleware.FieldSysID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSysID(v)
		return nil
	}
	return fmt.Errorf("unknown Middleware field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MiddlewareMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MiddlewareMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MiddlewareMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Middleware numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MiddlewareMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MiddlewareMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MiddlewareMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Middleware nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MiddlewareMutation) ResetField(name string) error {
	switch name {
	case middleware.FieldLID:
		m.ResetLID()
		return nil
	case middleware.FieldDID:
		m.ResetDID()
		return nil
	case middleware.FieldSysID:
		m.ResetSysID()
		return nil
	}
	return fmt.Errorf("unknown Middleware field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MiddlewareMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MiddlewareMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MiddlewareMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MiddlewareMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MiddlewareMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MiddlewareMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MiddlewareMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Middleware unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MiddlewareMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Middleware edge %s", name)
}
